### ISSUE TITLE
iPhone and Android exchanging multiple CENs

### ISSUE THREAD

**Issue by markingle** [covid19risk/covidwatch-ios#1]
@zssz per our conversation on Slack below is a link to a log file from Xcode showing the activity between a SAMSUNG Galaxy7 and iPhone 7 Plus - https://drive.google.com/file/d/1iPsSb8wtpUI_f-bQr7SDaAJAm2F8op96/view?usp=sharing

Also here is a link to a video showing the issue - https://drive.google.com/file/d/1rWJTTEXiniPW69mC8I8HkpO6rFEhTEz7/view?usp=sharing

The iOS app eventually crashes....let me know if you need the dump

**Comment by markingle** [comment]
@zssz Should we close this issue given the latest changes to integrate with TCN?

**Comment by zssz** [comment]
Yes.
