### ISSUE TITLE
Bug: Tester unable to install CW app (gets error alert saying "Unable to install CW Demo app"

### ISSUE THREAD

**Issue by mxie148** [covid19risk/covidwatch-ios#119]
The app is on her phone (but the logo looks grayed out and she gets an error alert saying "Unable to download CW app").

**Comment by mxie148** [comment]
@zssz -- here is an issue from a tester who is unable to download the iOS app. She keeps getting the attached images. Any troubleshooting tips? 

![](https://covidwatch.zendesk.com/attachments/token/jtaU1n6Q2q18ugpEISQ5lBnxI/?name=710BE39F-B5A6-4335-A6E2-1B9C2E5435DB.png)

![](https://covidwatch.zendesk.com/attachments/token/TzhlJryNKinxscqkwfunhVFVn/?name=EB291CFA-65B9-460D-8961-377B0C5B3B7C.png)

**Comment by zssz** [comment]
The tester tries to upload a copy of the app that doesn't have their UDIDs added. Instruct the tester to redownload the latest copy and upload that through iTunes.

This is the wrong repo to report this issue, as this is the TCN app.
