### ISSUE TITLE
Discovering new devices in the background

### ISSUE THREAD

**Issue by dwt** [covid19risk/covidwatch-ios#2]
Hi there,

I'm working on a similar application, that is (as far as I understand your project) is probably trying to give even more privacy guarantees. However, the bluetooth part seems very similarr, and I'm trying to find out if you have found a solution to continue to scan for new devices on iOS, while the app is in the background.

Our project: https://github.com/ito-org
Our Protocol Description: https://github.com/ito-org/STRICT

I'd love it if we could collaborate at least on a technical level, and at least ensure that the bluetooth advertisements are compatible / readable by the other apps.

**Comment by JaafarRammal** [comment]
I believe it is possible to link different apps through different Bluetooth processes as long as the device accepts specific channel identifiers from different "apps"

In this repo, as far as I understand, the identifier is hardcoded and only devices whose connection offers this identifier will be accepted to connect. You could make sure that your connection channel offers an identifier field and that the different app accepts your hardcoded identifier

**Comment by dwt** [comment]
That sounds great.

Did you guys already find a solution to the problem of communicating with other (iOS) devices while the app is in the background?

We are pretty confident that Android <-> Android works, as well as Android <-> iOS (Android can send iBeacons, which wake the iOS App), but iOS <-> iOS still eludes us, as Apple seems to not allow scanning vor new BLE devices or iBeacon sending in the background.

**Comment by zssz** [comment]
iOS 13.4 (and older) does not support the discoverability between third-party iOS apps in the suspended or background-running state, and with the devices' screens locked. Note: If the user unlocks the screen or launches an app (e.g., Settings.app), which does active Bluetooth scanning, then yes.

More details here: https://github.com/Co-Epi/CEN
